"""add_zoom_tokens_to_user

Revision ID: a6939b2844cf
Revises: e0b8b7fc0043
Create Date: 2026-01-21 23:28:20.783891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6939b2844cf'
down_revision: Union[str, Sequence[str], None] = 'e0b8b7fc0043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zoom_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('zoom_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('zoom_token_expires_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'zoom_auth_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zoom_auth_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'zoom_token_expires_at')
    op.drop_column('users', 'zoom_refresh_token')
    op.drop_column('users', 'zoom_access_token')
    # ### end Alembic commands ###
